version: '3'
services:
  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: DB
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./mysql:/val/lib/mysql
    ports:
      - 3306:3306
  web:
    container_name: web
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    working_dir: /workspace
    volumes:
      - .:/workspace
    ports:
      - 8000:8000
    depends_on:
      - db